name: Convert TS to M3U8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Download TS file
        run: |
          mkdir hls_output
          curl -o hls_output/input.ts "http://tv365.me:80/live/5794770199/3978448607/187263.ts"

      - name: Convert to M3U8
        run: |
          ffmpeg -i hls_output/input.ts -c:v copy -c:a copy \
          -f hls -hls_time 10 -hls_list_size 0 \
          -hls_segment_filename "hls_output/segment_%03d.ts" \
          hls_output/playlist.m3u8

      - name: Upload to repo
        run: |
          cp -r hls_output/* .
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Added HLS stream"
          git push
